### ISSUE TITLE
Parameter __repr__ recursion in Python 3.8

### ISSUE THREAD

**Issue by NiceneNerd** [leoetlino/aamp#5]
At least one of the non-dataclass parameter types, `U32`, doesn't work properly in Python 3.8. Attempting to dump YAML gives a recursion error in its `__repr__` method, like so:

```
Traceback (most recent call last):
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/__main__.py", line 43, in <module>
    main()
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/__main__.py", line 40, in main
    do_aamp_to_yml(input_data, output)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/__main__.py", line 13, in do_aamp_to_yml
    output.write(aamp.converters.aamp_to_yml(input_data))
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/converters.py", line 14, in aamp_to_yml
    return yaml.dump(root, Dumper=dumper, allow_unicode=True, encoding='utf-8', default_flow_style=None)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 114, in represent_param_io
    return represent_mapping(dumper, '!io', {
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 24, in represent_mapping
    node_value = dumper.represent_data(item_value)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 107, in represent_param_list
    return represent_mapping(dumper, '!list', {
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 24, in represent_mapping
    node_value = dumper.represent_data(item_value)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 38, in represent_dict
    return represent_mapping(dumper, 'tag:yaml.org,2002:map', mapping, flow_style)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 24, in represent_mapping
    node_value = dumper.represent_data(item_value)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 102, in represent_param_object
    return represent_mapping(dumper, '!obj',
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 24, in represent_mapping
    node_value = dumper.represent_data(item_value)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/yaml_util.py", line 158, in <lambda>
    yaml.add_representer(U32, lambda d, data: d.represent_scalar('!u', str(data)), Dumper=dumper)
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/parameters.py", line 120, in __repr__
    return f'U32({self})'
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/parameters.py", line 120, in __repr__
    return f'U32({self})'
  File "/home/mrm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/aamp/parameters.py", line 120, in __repr__
    return f'U32({self})'
  [Previous line repeated 322 more times]
RecursionError: maximum recursion depth exceeded while getting the str of an object
```

It seems that something has changed in 3.8 that makes `__repr__` call itself in the f-string it returns. Probably related to [this](https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior)? 
> Removed \_\_str\_\_ implementations from builtin types bool, int, float, complex and few classes from the standard library. They now inherit \_\_str\_\_() from object. As result, defining the \_\_repr\_\_() method in the subclass of these classes will affect their string representation. (Contributed by Serhiy Storchaka in bpo-36793.)

**Comment by leoetlino** [comment]
Hmm, yes, that's probably the reason it stopped working. Does replacing `self` with `super().__repr__()` work?

**Comment by leoetlino** [comment]
This has been fixed for a while now, I think.
