### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'CDumper'

### ISSUE THREAD

**Issue by zardini123** [leoetlino/aamp#8]
I am trying to use aamp_to_yml on macOS 10.14 and I got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aamp_to_yml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/aamp/__main__.py", line 40, in main
    do_aamp_to_yml(input_data, output)
  File "/usr/local/lib/python3.8/site-packages/aamp/__main__.py", line 13, in do_aamp_to_yml
    output.write(aamp.converters.aamp_to_yml(input_data))
  File "/usr/local/lib/python3.8/site-packages/aamp/converters.py", line 9, in aamp_to_yml
    dumper = yaml.CDumper
AttributeError: module 'yaml' has no attribute 'CDumper'
```

**Comment by leoetlino** [comment]
It looks like PyYAML's C module is not available on your system... You may need to install libyaml (via homebrew, maybe?) and then reinstall the PyYAML package to make pip compile and install the C module

**Comment by zardini123** [comment]
I installed libyaml via brew, uninstalled pyyaml, reinstalled pyyaml, and its still happening.  Thoughts?

**Comment by leoetlino** [comment]
Try

```
LDFLAGS="-L$(brew --prefix)/lib" \
  CFLAGS="-I$(brew --prefix)/include" \
  pip3 install --global-option="--with-libyaml" --force pyyaml
```

**Comment by zardini123** [comment]
Perfection.  I would really appreciate it if you put this information in the readme for future users.  Thanks!

(Or, is there some way to get the library to link without this reinstall?)

**Comment by tallywiesenberg** [comment]
Hey crew, I've actually run into this same problem on my own [project](https://github.com/tellor-io/pytelliot/). Two questions:
- @zardini123 did you encounter this error on an m1 Mac with ARM architecture? I am on an m1 mac and I ran into this bug.
- @leoetlino Has anyone found a cleaner workaround since? I am looking to provide a workaround for m1 mac users in my documentation.

Thanks!

**Comment by leoetlino** [comment]
Have you tested PyYAML 5.4.1 (which is currently the latest version)? If 5.4.1 still isn't built with libyaml then you'll need to ask the PyYAML packagers or maintainers to release binary wheels for macOS with libyaml enabled.
